# Identifikacija
sonar.projectKey=Majst0rL_TraceBit
sonar.organization=majst0rl
sonar.projectName=TraceBit
sonar.projectVersion=1.0

# Glavni jezik
sonar.language=ts

# Lokacija kode
sonar.sources=backend,frontend
sonar.tests=backend/tests

# Dovoli samo določene tipe datotek
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.spec.ts,**/__tests__/**

# Python coverage (backend)
sonar.python.coverage.reportPaths=coverage.xml

# (če boš delal coverage za frontend, dodaš še spodnjo vrstico)
# sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Kodiranje
sonar.sourceEncoding=UTF-8
